services:
  app:
    container_name: app
    build: ./app
    # ports:
    #   - "3000:3000"
    expose:
      - "3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    develop:
      watch:
        - path: ./app
          action: rebuild
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M

  sandbox:
    container_name: sandbox
    build: ./sandbox
    hostname: ubuntu
    init: true
    tty: true
    security_opt:
      - no-new-privileges:true
    network_mode: none
    restart: always
    develop:
      watch:
        - path: ./sandbox
          action: rebuild
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M

  caddy:
    container_name: caddy
    image: caddy:latest
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - caddy_data:/data
    command: caddy reverse-proxy --from ca.zimo.li --to app:3000

volumes:
  caddy_data:
