services:
  app:
    container_name: app
    build: ./app
    ports:
      - "3000:3000"
    expose:
      - "3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    develop:
      watch:
        - path: ./app
          action: rebuild
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M

  sandbox:
    container_name: sandbox
    build: ./sandbox
    hostname: ubuntu
    init: true
    tty: true
    restart: always
    security_opt:
      - no-new-privileges:true
    network_mode: none
    develop:
      watch:
        - path: ./sandbox
          action: rebuild
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
