services:
  app:
    container_name: app
    build: .
    hostname: toronto
    ports:
      - "3000:3000"
    init: true
    restart: always
    develop:
      watch:
        - path: ./src
          action: rebuild
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M

  restarter:
    container_name: restarter
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      sh -c "while sleep 1800; do docker restart app; done"
