services:
  app:
    container_name: app
    build: ./app
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M

  sandbox:
    container_name: sandbox
    build: ./sandbox
    hostname: ubuntu
    init: true
    tty: true
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    network_mode: none
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 50M
